package dto

import "time"

// ReminderCreateRequest is the payload for creating a care reminder.
type ReminderCreateRequest struct {
	PlantSpeciesID uint      `json:"plant_species_id"`
	GardenID       uint      `json:"garden_id"`
	TaskTitle      string    `json:"task_title" binding:"required,max=255"`
	RemindDate     time.Time `json:"remind_date" binding:"required"`
	Frequency      string    `json:"frequency" binding:"omitempty,max=32"`
}

// ReminderStatusRequest carries the new status for a reminder.
type ReminderStatusRequest struct {
	Status string `json:"status" binding:"required"`
}

// ReminderUpdateRequest changes the schedule of a reminder series. When
// remind_date or frequency changes, the pre-generated next occurrence is
// invalidated (schedule_version bumps) and recalculated.
type ReminderUpdateRequest struct {
	TaskTitle  *string    `json:"task_title" binding:"omitempty,max=255"`
	RemindDate *time.Time `json:"remind_date"`
	Frequency  *string    `json:"frequency" binding:"omitempty,max=32"`
}

// ReminderCompleteResult is returned by the idempotent complete endpoint.
// Processed is false on a repeated tap: the next occurrence was already
// generated by the first request and the client shows "already processed".
type ReminderCompleteResult struct {
	Reminder       ReminderView `json:"reminder"`
	Processed      bool         `json:"processed"`
	NextReminderID uint         `json:"next_reminder_id"`
	Message        string       `json:"message"`
}

// ReminderView is a reminder enriched with its plant source and pot status.
type ReminderView struct {
	ID              uint      `json:"id"`
	UserID          uint      `json:"user_id"`
	PlantSpeciesID  uint      `json:"plant_species_id"`
	GardenID        uint      `json:"garden_id"`
	SeriesID        uint      `json:"series_id"`
	Seq             int       `json:"seq"`
	ScheduleVersion int       `json:"schedule_version"`
	TaskTitle       string    `json:"task_title"`
	RemindDate      time.Time `json:"remind_date"`
	Frequency       string    `json:"frequency"`
	Status          string    `json:"status"`
	CreatedAt       time.Time `json:"created_at"`

	// Source information rendered by the UI.
	PlantName   string `json:"plant_name"`
	PlantType   string `json:"plant_type"`
	PlantAlias  string `json:"plant_alias"`
	GardenName  string `json:"garden_name"`
	Location    string `json:"location"`
	GardenStatus string `json:"garden_status"`
	SourceLabel string `json:"source_label"`
}

// GardenTransferRequest assigns awaiting reminders to another pot.
type GardenTransferRequest struct {
	TargetGardenID uint `json:"target_garden_id" binding:"required"`
}
